apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "charts.fullname" . }}-manager-role
  labels:
  {{- include "charts.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - apiserveroverloads
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - apiserveroverloads/finalizers
  verbs:
  - update
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - apiserveroverloads/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - commandinjections
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - commandinjections/finalizers
  verbs:
  - update
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - commandinjections/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - configmapdestroyers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - configmapdestroyers/finalizers
  verbs:
  - update
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - configmapdestroyers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - consumenamespaceresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - consumenamespaceresources/finalizers
  verbs:
  - update
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - consumenamespaceresources/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - containerresourcechaos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - containerresourcechaos/finalizers
  verbs:
  - update
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - containerresourcechaos/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - cordonnodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - cordonnodes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - eventsentropies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - eventsentropies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - nodedestroyers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - nodedestroyers/finalizers
  verbs:
  - update
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - nodedestroyers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - nodetainters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - nodetainters/finalizers
  verbs:
  - update
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - nodetainters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - poddestroyers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - poddestroyers/finalizers
  verbs:
  - update
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - poddestroyers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - podlabelchaos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - podlabelchaos/finalizers
  verbs:
  - update
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - podlabelchaos/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - randomscalings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - randomscalings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - secretdestroyers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - secretdestroyers/finalizers
  verbs:
  - update
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - secretdestroyers/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "charts.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: khaos
    app.kubernetes.io/part-of: khaos
  {{- include "charts.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "charts.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "charts.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'