# permissions for end users to edit commandinjections.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: commandinjection-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: khaos
    app.kubernetes.io/part-of: khaos
    app.kubernetes.io/managed-by: kustomize
  name: commandinjection-editor-role
rules:
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - commandinjections
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - commandinjections/status
  verbs:
  - get
