---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - chaos.stackzoo.io
  resources:
  - podlabelchaos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - chaos.stackzoo.io
  resources:
  - podlabelchaos/finalizers
  verbs:
  - update
- apiGroups:
  - chaos.stackzoo.io
  resources:
  - podlabelchaos/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - commandinjections
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - commandinjections/finalizers
  verbs:
  - update
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - commandinjections/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - configmapdestroyers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - configmapdestroyers/finalizers
  verbs:
  - update
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - configmapdestroyers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - containerresourcechaos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - containerresourcechaos/finalizers
  verbs:
  - update
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - containerresourcechaos/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - nodedestroyers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - nodedestroyers/finalizers
  verbs:
  - update
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - nodedestroyers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - poddestroyers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - poddestroyers/finalizers
  verbs:
  - update
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - poddestroyers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - secretdestroyers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - secretdestroyers/finalizers
  verbs:
  - update
- apiGroups:
  - khaos.stackzoo.io
  resources:
  - secretdestroyers/status
  verbs:
  - get
  - patch
  - update
