apiVersion: khaos.stackzoo.io/v1alpha1
kind: PodLabelChaos
metadata:
  labels:
    app.kubernetes.io/name: podlabelchaos
    app.kubernetes.io/instance: podlabelchaos-sample
    app.kubernetes.io/part-of: khaos
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: khaos
  name: podlabelchaos-sample
spec:
  # TODO(user): Add fields here
