# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/khaos.stackzoo.io_poddestroyers.yaml
- bases/khaos.stackzoo.io_nodedestroyers.yaml
- bases/khaos.stackzoo.io_secretdestroyers.yaml
- bases/khaos.stackzoo.io_containerresourcechaos.yaml
- bases/khaos.stackzoo.io_commandinjections.yaml
- bases/khaos.stackzoo.io_podlabelchaos.yaml
- bases/khaos.stackzoo.io_configmapdestroyers.yaml
- bases/khaos.stackzoo.io_apiserveroverloads.yaml
- bases/khaos.stackzoo.io_eventsentropies.yaml
- bases/khaos.stackzoo.io_consumenamespaceresources.yaml
- bases/khaos.stackzoo.io_cordonnodes.yaml
- bases/khaos.stackzoo.io_nodetainters.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- path: patches/webhook_in_poddestroyers.yaml
#- path: patches/webhook_in_nodedestroyers.yaml
#- path: patches/webhook_in_secretdestroyers.yaml
#- path: patches/webhook_in_containerresourcechaos.yaml
#- path: patches/webhook_in_commandinjections.yaml
#- path: patches/webhook_in_podlabelchaos.yaml
#- path: patches/webhook_in_configmapdestroyers.yaml
#- path: patches/webhook_in_apiserveroverloads.yaml
#- path: patches/webhook_in_eventsentropies.yaml
#- path: patches/webhook_in_consumenamespaceresources.yaml
#- path: patches/webhook_in_cordonnodes.yaml
#- path: patches/webhook_in_nodetainters.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- path: patches/cainjection_in_poddestroyers.yaml
#- path: patches/cainjection_in_nodedestroyers.yaml
#- path: patches/cainjection_in_secretdestroyers.yaml
#- path: patches/cainjection_in_containerresourcechaos.yaml
#- path: patches/cainjection_in_commandinjections.yaml
#- path: patches/cainjection_in_podlabelchaos.yaml
#- path: patches/cainjection_in_configmapdestroyers.yaml
#- path: patches/cainjection_in_apiserveroverloads.yaml
#- path: patches/cainjection_in_eventsentropies.yaml
#- path: patches/cainjection_in_consumenamespaceresources.yaml
#- path: patches/cainjection_in_cordonnodes.yaml
#- path: patches/cainjection_in_nodetainters.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# [WEBHOOK] To enable webhook, uncomment the following section
# the following config is for teaching kustomize how to do kustomization for CRDs.

#configurations:
#- kustomizeconfig.yaml
