name: CI
on:
  push:
    branches:
      - main
    paths:
      - '**/*'
      - '!README.md'
      - '!docs/**'
  pull_request:
    paths:
      - '**/*'
      - '!README.md'
      - '!docs/**'

permissions:
  contents: read

jobs:
  golangci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
      - name: Linting examples manifests
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: examples/
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: '-exclude=G404,G204,G601 ./...'

