name: linting
on:
  push:
    branches:
      - main
    paths:
      - '**/*'
      - '!README.md'
      - '!docs/**'
  pull_request:
    paths:
      - '**/*'
      - '!README.md'
      - '!docs/**'

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
